### ISSUE TITLE
Checklist for repository content and structure

### ISSUE THREAD

**Issue by egonw** [PRA3006-Group/Repository#2]
# Repository Structure

The follow checks are meant to reflect good practices of scientific coding. See the [course literature list](https://github.com/egonw/pils/blob/master/index.md#literature) for some reading and context. The files can be written as plain text or as [Markdown](https://www.markdownguide.org/getting-started) (more readable). 

## Respository content

- [x] contains a LICENSE file
- [x] contains an AUTHORS file
- [x] contains an README file
- [x] old redundant and temporary test files have been removed
- [x] there is a logical folder structure

## Documentation

- [x] functions and methods are documented

## README

The README explains:

- [x] how your code should be run by a new user
